name: teledart
description: A Dart library interfacing with the latest Telegram Bot API.
version: 0.1.6
homepage: https://github.com/DinoLeung/TeleDart
issue_tracker: https://github.com/DinoLeung/TeleDart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0
  http: ^0.13.0

dev_dependencies:
  test: ^1.16.2
  build_runner: ^1.11.1
  json_serializable: ^4.0.0
  pedantic: ^1.10.0
